apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: mynginx
  type: NodePort
status:
  loadBalancer: {}
